version: "2"

services:
  web:
    build: ./web
    volumes:
      - ./web:/opt/web
    ports:
      - 7400:3000
    depends_on:
      - server
    restart: unless-stopped
    command: bash -c "npm install -y && npm run dev"

  server:
    build: ./server
    volumes:
      - ./server:/opt/web
    ports:
      - 7500:80
    depends_on:
      - crate
    restart: unless-stopped
    tty: true
    stdin_open: true

  crate:
    image: crate
    ports:
      - 4204:4200
      - 4304:4300
    environment:
      CRATE_HEAP_SIZE: 1g
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    volumes:
      - /mnt/data/crate/emulation:/data
    command: crate -Cnetwork.host=_site_
    restart: unless-stopped
